# Generated by Django 4.2.7 on 2023-12-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empname', models.CharField(max_length=50)),
                ('EmpID', models.IntegerField()),
                ('Designation', models.CharField(max_length=50)),
                ('DateofJoining', models.IntegerField()),
                ('Department', models.CharField(max_length=50)),
                ('SalaryPackage', models.IntegerField()),
                ('Experience', models.IntegerField()),
            ],
        ),
    ]
